
3D printed truck


Copyright (C) 2012-2021 Adam Williams <broadcast at earthling dot net>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA








What you'll find here:


arm_cam.c: camera motor receiver

arm_car.c: 2 wheel robot driven by direct drive, sensored brushless motors

arm_cc1101.c: 433Mhz radio library for the ARM

arm_truck.c, arm_truck.h: the lunchbox firmware

arm_xbee.c: xbee library for the ARM

cam_remote.X: camera remote control

car.s: vehicle firmware for the G buggy

car_remote.s: orginal assembly language remote for CC1101 & XBee

car_remote.X: 3D printed vehicle remote control

car_receive.X: 3D printed vehicle receiver

car_remote.X.bak: failed remote for the XBee with frequency hopping

freq_hops.ods: frequency hopping plot to aid in spreading the frequencies

fuse.X: a software fuse

truck3.pcb: last layout for the tamiya board






=============================================================================
3D printed truck

arm_truck2.c, arm_truck2.h: the 3D printed truck firmware

a1323.pcb: hall effect sensor board for motor sensor

l6234.pcb: H bridge board for motor

imu4.pcb: IMU for 3D printed truck


cring.FCStd: retaining ring for the motors
    .4mm nozzle
    .2mm layer height out of PETG
    no cooling fan

tire2.FCMacro: generate procedural tire.  Not used anymore.
    requires creating a rigid body 1st
    .28mm layer height
    .8mm line width
    1.6mm wall thickness
    1.4mm top/bottom thickness
    100% infill
    no support
    230 printing temp
    0 bed temp
    20mm print speed
    no retraction

tire6.FCMacro: latest honeycomb tire
    must extrude by 1 layer height, then run helix.c to generate a helix by 
    creating discrete layers
    must enable timelapse mode with fixcura.py to fix stringing
    tires must be mirror images or the truck will pull to 1 side

front_tire3.FCStd: front tire
    Import STL into blender
    Run helix.py to make the struts a helix
    Export new layers as an STL file
    print with .8mm nozzle
    TPU
    .32mm layer height
    left & right must be mirror images
    timelapse mode with fixcura.py has better stringing


rear_tire3.FCStd: most recent honecomb rear tire/wheel design
    print hub cap in PLA 
        .4mm nozzle .32mm layer height
    tire model is a mockup
    left & right must be mirror images
    single .32mm layer of onroad tire must be exported as STL, then extruded with
        helix.c 31mm total height, no V tread, 20 deg rotation


truck_radio.pcb: remote control tx/rx for 3D printed truck & the camera

truck4.pcb: mane board for 3D printed truck


ball.FCStd: 
    ball link
    print with ball.3mf
    
    TODO: round edge for servo clearance

bumper.FCStd:
    bumper for the front of the angle rods
    print in TPU


container.FCStd:
    print masks have to be booleaned with panels in Blender
    Handle doesn't attach right on the print mask seam.  It attaches 1/2 a triangle behind it.

    top corner master:
    bottom corner master:
        require .32 layers 230C for adhesion
        

    container budget:
    radio panel: 42, 32
    back left: 42, 23
    back right: 36, 25
    bottom right rear: 43, 27
    right rear: 65, 40
    left rear: 65, 40
    right front: 57, 35
    left front: 57, 35
    bottom right front: 42, 26
    front right: 44, 25
    front left: 44, 27
    bottom left front: 38, 24
    bottom left rear: 40, 25

    TODO: shift cable hole right.  Create tab for aligning handle.

container.FCMacro:
    scripts for creating the container
    

radio_box.FCStd:
    container for radio modules & switches.
    use print mask to create wall & isogrid parts
    walls contain temporary plastic stringers to aid gluing
    print without support & with print cooling to bridge overhangs
    rotate it to bridge overhangs
    TODO: 
        Tabs to aid alignment
        hollow border
        shift cable hole left

tool.FCStd: socket wrench for 6-32 locknuts

traction.FCMacro: create objects for traction

traction.FCStd: traction section
    .8mm nozzle, .32mm layer height, no support
    battery walls:
        print fillet side up so the laminations are the right way.
    latch pivot
    back, front, door:
        fillet on top
        support to base only, 80 degrees
    bottom, electronicals:
        no support
    right side:
        side cutout
        hinge
        captive nuts

    union for both sides (motor support | side cutout) & side mask
    union for both sides (motor support & motor mask)
    union for both sides (motor support | side cutout) & bottom mask
     - boolean error causes it to not print mirrored side.  Use cura mirror instead.
    union for both sides (motor support | side cutout) & top mask

    TODO: captive nuts for angle rod farsteners





steering.FCMacro:
    create objects for steering

steering.FCStd: steering section
    print with 1mm nozzle 
    .2mm layer height
    ultimaker project: steering.3mf
    bottom cutout
    wheel vertical
     - print sideways
    wheel vertical mirror001
    wheel fork master
    fusion: fork bridge + wheel vertical003
    servo bathtub
    - support to bed only






front_wheel.FCStd: front wheel
    modeled for a .4mm nozzle

rear_wheel.FCStd: OBSOLETE motor wheel coupling
    print with 1mm nozzle
    .8mm line width
    .32mm layer height
    ultimaker project: front_wheel.3mf, rear_wheel.3mf
    print unions with print mask
    print rings
    no support


motor3.FCStd: motor mount
    The following use .8mm nozzle, .32 layer height, support with 80deg overhang
    shroud
    tpu out of TPU
    clamp * 4
    motor plate
    TODO: 4-40 locknuts in motor plate

    The following use .4mm nozzle, .2mm layer
    SENSOR PLATE
        .8mm top/bottom thickness
    MAGNET HOLDER
        PETG
        support to base
        .4mm nozzle 
    GASKET:
        TPU .4mm nozzle .32mm layer



car_remote.FCMacro:
    create objects for car_remote

car_remote.FCStd: remote control for vehicle
    disable support for the top & bottom
    use support only for the joysticks
    no ironing
    .4mm nozzle
    .8mm top/bottom thickness
    1.2mm wall thickness
    skirt
    bottom, top:
        expand all clones
        select base of mirror
        select visible objects
        no support
        print with outside facing the bed
    steering pivot, throttle pivot:
        don't export magnets
        use support from magnet holder to bed
    steering lever, throttle lever:
        use support from short side of hinge to bed
    covers for power, increase speed, decrease speed:
        no support
        with wide part facing bed
    TODO:
        use single layer bridge instead of support for screw holes
        holes for temporary screws






charger.FCStd: charging stand for a Qi charger
    print with .4mm nozzle, .4mm line width, no support





filament budget for traction module:
motor mounts: 39g * 2
bottom: 55g
sides: 49g * 2
front, rear, door, battery walls:  55g


===========================================================================

Carbon fiber farsteners for a fixed gopro

Key files:

isogrid_plane.FCMacro:
    create isogrids for cam_remote, car_remote, & cam_gearbox.FCStd

clamshell.FCMacro:
    create walls for cam_remote, car_remote

gopro_case.FCStd: case for a gopro 7
    print case union with print mask
    print case cut with print mask & all base objects
    print with support everywhere, lesser overhangs facing up
    skirt adhesion
    TODO: copy hinges from gopro_to_wood
     - knobs for the wire bits



gopro_to_wood.FCStd: case for mounting a gopro 7 behind a sheet of wood
    print case union with print mask
    print case cut with print mask
    print with support everywhere, lesser overhangs facing up
    skirt adhesion

gopro4_to_wood.FCStd: case for mounting a gopro 4 behind a sheet of wood


gopro.FCStd
    top endpiece for carbon fiber
        print with laminations distributing plasic flex along right angles
        support everywhere
    
    bottom endpiece

    both endpieces need "outer shroud" + "bolt loop"
        print with laminations perpendicular to shaft
    
    4 * "inner shroud slice" for the top & bottom endpieces
        print with laminations distributing plastic flex along curves

    bottom needs "base"
    
    top needs "cam"

=============================================================================

Panning mount:

cam_remote.pcb, cam.pcb: electronicals

cam_gearbox2.FCStd:
    brushless servo as a stepper motor for panning

cam_gearbox.FCStd: OBSOLETE
    hobby motor as a stepper motor
    4.5:1 gear reduction for panning motor
    walls have to be printed with .4mm thick tops & bottoms
        to get smooth surfaces
    print pinion with gear on bottom & no support
    install pinion with hex facing motor hex

cam_remote.FCStd:
    remote control for camera panner
    no ironing
    no horizontal expansion
    .4mm nozzle
    .8mm top/bottom thickness
    1.2mm wall thickness
    support with 60 deg overhang angle
    skirt
    60C bed temp
    support to bed only except for top & bottom
    top, bottom:
        block support over all except edges with switch covers
        print with outside facing the bed
        .8mm top & bottom thickness to get smooth 2mm sheets
        print top with spring holder but not spring
    lever, steering:
        print with support on flatter side
        don't print magnets
    power, increase, decrease cover:
        print with no support
    top switch cover, bottom switch cover:
        support everywhere

TODO:
    transition layers still off
    vertical gap between magnets & sensors
    reverse clamshell
    make shafts part of clamshell instead of levers
    use single layer bridge instead of support for screw holes




gopro_bearing.FCStd:
    bearing for motorized panning
    print bearing inner
    print bearing outer
     - doesn't require support
    must print with
        4 * "inner shroud slice"
         - TODO: make hole for tube & make base wider to compensate for lost material
         - TODO remove alignment ring to make it easier to print
        "outer shroud" + "bolt loop"
    
    print right angle coupling with right hole pattern to create a right angle
    requires ironing


gopro_rightangle.FCStd
    cf collar - print 2 for the bearing in place of the inner shroud slice & 2 for the handle
        100% infill

    old right angle coupling between carbon fiber & handle
    print with no support
    print with laminations distributing plastic flex along curves

    attachment + attachment mirror are required


gopro_motor.FCStd:
    coupling to motor for panning without a gearbox
    must print with
        4 * "inner shroud slice"
         - TODO: make hole for motor shaft & make base wider to compensate for lost material
        "outer shroud" + "bolt loop"

shroud.FCStd:
    the shroud for a direct drive panner
    tube segment was created with 
    ./tube shroud.stl 30 60 0 16
    print with .4mm line width
    205C filament 60C bed




15mph/1185rpm on 12V with no load
4248 traction motors with 108mm tires:
20 turns 26 AWG


272rpm on 10V with no load
70 turns * 32 AWG

Maximum windings: 25 turns * 26AWG
75 turns * 32 AWG


RPM = C constant * V voltage * A wire cross section

















